hold on
fig = plot(t,errh);
xlabel('t');
ylabel('Y');
title(strcat('Y=|h(t)-h_s|: eps=',num2str(eps),', k=',num2str(k), ...
    ', D_',num2str(optionb(1,optionsn)),'(u)=(', ... 
    num2str(optionb(3,optionsn)),')+(1-(', ...
    num2str(optionb(3,optionsn)),'))u, Nx=',num2str(Nx)));    
hold off

filename = [strcat('Y=abs(h(t)-h_s)_eps=',num2str(eps),'_k=', ... 
            num2str(k),'_D_',num2str(optionb(1,optionsn)), ... 
            '(u)=(',num2str(optionb(3,optionsn)),')+(1-(', ...
            num2str(optionb(3,optionsn)),'))u_Nx=', ...
            num2str(Nx),'.jpg')];         
saveas(fig,filename);
close all;
clear fig;

hold on
fig = plot(t,errv);
xlabel('t');
ylabel('Y');
title(strcat('Y=||v(t,cdot)-v_s||_{\infty}: eps=',num2str(eps), ... 
    ', k=',num2str(k),', D_',num2str(optionb(1,optionsn)),'(u)=(', ...
    num2str(optionb(3,optionsn)),')+(1-(', ...
    num2str(optionb(3,optionsn)),'))u, Nx=',num2str(Nx)));    
hold off

filename = [strcat('Y=norm(v(t,cdot)-v_s)_infty_eps=',num2str(eps), ... 
            '_k=',num2str(k),    '_D_',num2str(optionb(1,optionsn)), ... 
            '(u)=(',num2str(optionb(3,optionsn)),')+(1-(', ...
            num2str(optionb(3,optionsn)),'))u Nx=', ... 
            num2str(Nx),'.jpg')];    
saveas(fig,filename);
close all;
clear fig;
